spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/micro_services?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
server:
  port: 8888